CREATE TABLE support_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(32) NOT NULL CHECK (role IN ('SUPPORT_AGENT', 'SENIOR_SUPPORT', 'ADMIN')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer (
    id BIGINT PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE support_ticket (
    id BIGINT PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    title VARCHAR(240) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('OPEN', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED')),
    priority VARCHAR(32) NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    assigned_user_id BIGINT NOT NULL REFERENCES support_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ticket_assigned_updated ON support_ticket(assigned_user_id, updated_at DESC);
CREATE INDEX idx_ticket_customer ON support_ticket(customer_id);

CREATE TABLE ticket_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES support_ticket(id),
    event_type VARCHAR(64) NOT NULL,
    description TEXT NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ticket_event_history ON ticket_event(ticket_id, created_at);

CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer(id),
    order_number VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL CHECK (status IN ('PROCESSING', 'SHIPPED', 'DELAYED', 'DELIVERED', 'CANCELLED')),
    tracking_number VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL,
    estimated_delivery_date DATE NOT NULL
);
CREATE INDEX idx_customer_order_customer ON customer_order(customer_id);

CREATE TABLE service_status (
    service_name VARCHAR(80) PRIMARY KEY,
    status VARCHAR(32) NOT NULL CHECK (status IN ('OPERATIONAL', 'DEGRADED', 'OUTAGE')),
    public_message VARCHAR(500) NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE human_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES support_ticket(id),
    proposed_action VARCHAR(48) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ,
    reviewed_by VARCHAR(255),
    review_note VARCHAR(1000)
);
CREATE INDEX idx_review_status_created ON human_review(status, created_at DESC);
CREATE UNIQUE INDEX uq_pending_review_ticket_action ON human_review(ticket_id, proposed_action) WHERE status = 'PENDING';

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(255) NOT NULL,
    action VARCHAR(80) NOT NULL,
    resource_type VARCHAR(80) NOT NULL,
    resource_id VARCHAR(100) NOT NULL,
    result VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_event_created ON audit_event(created_at DESC);

CREATE TABLE supportai_kb_ingestion (
    document_key VARCHAR(160) PRIMARY KEY,
    content_hash VARCHAR(64) NOT NULL,
    chunk_count INTEGER NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
